# Generated by Django 4.2 on 2023-05-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tenant_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_reg_no', models.CharField(blank=True, max_length=100)),
                ('company_pan_no', models.CharField(blank=True, max_length=100)),
                ('tenant_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tenantregister',
            },
        ),
    ]
