# Generated by Django 4.2 on 2023-05-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('logo_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('key_param', models.JSONField()),
                ('d_type', models.JSONField()),
            ],
            options={
                'db_table': 'conn',
            },
        ),
        migrations.CreateModel(
            name='tenant_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_reg_no', models.CharField(blank=True, max_length=100)),
                ('company_pan_no', models.CharField(blank=True, max_length=100)),
                ('tenant_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tenantregister',
            },
        ),
        migrations.CreateModel(
            name='connection_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_detail', models.CharField(max_length=100)),
                ('con_str', models.JSONField()),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('last_modified_on', models.DateField(auto_now=True, null=True)),
                ('created_on', models.DateField(auto_now=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_id', to='login_app.conn')),
                ('tenant_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.tenant_user')),
            ],
            options={
                'db_table': 'connection_detail',
            },
        ),
    ]
